// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bcd_tggl_fit_cpp
Rcpp::List bcd_tggl_fit_cpp(const arma::mat& X, const arma::mat& Y, const Rcpp::NumericVector& lambdas, const Rcpp::List& indices_list, const Rcpp::NumericVector& weight_vec, const Rcpp::IntegerVector& node_order, const int max_iter, const double tol, const bool verbose, const Rcpp::Nullable<arma::mat> init, const Rcpp::Nullable<arma::mat> omega);
RcppExport SEXP _tggl_bcd_tggl_fit_cpp(SEXP XSEXP, SEXP YSEXP, SEXP lambdasSEXP, SEXP indices_listSEXP, SEXP weight_vecSEXP, SEXP node_orderSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP, SEXP initSEXP, SEXP omegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type lambdas(lambdasSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type indices_list(indices_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type weight_vec(weight_vecSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type node_order(node_orderSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<arma::mat> >::type init(initSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<arma::mat> >::type omega(omegaSEXP);
    rcpp_result_gen = Rcpp::wrap(bcd_tggl_fit_cpp(X, Y, lambdas, indices_list, weight_vec, node_order, max_iter, tol, verbose, init, omega));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tggl_bcd_tggl_fit_cpp", (DL_FUNC) &_tggl_bcd_tggl_fit_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_tggl(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
