# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bcd_tggl_fit_cpp <- function(X, Y, lambdas, indices_list, weight_vec, node_order, max_iter = 100L, tol = 1e-6, verbose = FALSE, init = NULL, omega = NULL) {
    .Call(`_tggl_bcd_tggl_fit_cpp`, X, Y, lambdas, indices_list, weight_vec, node_order, max_iter, tol, verbose, init, omega)
}

